/**
 * Regenerates pdf/fonts.css: the Archivo webfont subsets the deck uses,
 * inlined as base64 so the PDF build runs offline and the PDF embeds its fonts.
 *
 *   node pdf/tools/fetch-fonts.mjs
 *
 * Only needs re-running if the brand typeface changes.
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'fonts.css');
const GF = 'https://fonts.googleapis.com/css2?family=Archivo:wght@300;400;500;600;700;800;900&display=swap';
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const curl = (url, binary) =>
  execFileSync('curl', ['-sS', '--fail', '-A', UA, url], { maxBuffer: 1 << 26, encoding: binary ? null : 'utf8' });

const css = curl(GF, false);

// Keep only the subsets the deck's Spanish/English copy needs.
const faces = css
  .split('/*')
  .slice(1)
  .map((b) => '/*' + b)
  .filter((b) => /^\/\*\s*(latin|latin-ext)\s*\*\//.test(b));

let out = '/* Archivo — self-hosted for the PDF build. Generated by pdf/tools/fetch-fonts.mjs. */\n';
for (const face of faces) {
  const url = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1];
  if (!url) continue;
  const b64 = Buffer.from(curl(url, true)).toString('base64');
  out += face
    .replace(/^\/\*[^*]*\*\/\s*/, '')
    .replace(/url\(https:\/\/[^)]+\)/, `url(data:font/woff2;base64,${b64})`)
    .replace(/font-display:\s*swap;/, 'font-display: block;');
}

fs.writeFileSync(OUT, out);
console.log(`pdf/fonts.css — ${faces.length} faces, ${(out.length / 1024).toFixed(0)} KB`);
